apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-check-deployment
  namespace: web-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-check
  template:
    metadata:
      labels:
        app: web-check
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: web-check
        image: lissy93/web-check
        ports:
        - containerPort: 3000
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000  # Using a non-zero UID to ensure it's not running as root
          capabilities:
            drop:
              - ALL  # Drop all Linux capabilities unless explicitly needed
