apiVersion: v1
kind: Service
metadata:
  name: web-check-service
  namespace: web-check
spec:
  selector:
    app: web-check
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30006  # You can specify a node port in the range 30000-32767
  type: NodePort
